### ISSUE TITLE
Can't load VisualStudio project file

### ISSUE THREAD

**Issue by pfedick** [Freestyle00/Super_Marios_Bros#1]
When double clicking on "Super_Marios_Bros.sln" the project does not load and I get the following error message:

![image](https://user-images.githubusercontent.com/13393110/124950648-e6bb4d80-e012-11eb-98e4-bd59ef3547cc.png)

I have installed Visual Studio 2019 with C# and  the .NET Framework 4.7.1 Developer Pack. It seems there is still something missing.

I have no problem to load your other project "Bullet_Game_PT1".

Patrick

**Comment by vchelaru** [comment]
You need to install MonoGame 3.7 for visual studio here:

https://community.monogame.net/t/monogame-3-7/10971
